[package]
name = "Ansome-AI-Collection"
version = "0.1.0"
edition = "2018"
authors = [
    "Alex Thomas <ansome22@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.14"